### ISSUE TITLE
Рукописные иконы на заказ в Москве

### ISSUE THREAD

**Issue by htmlblog** [htmlblog/demo#3]
Иконописная мастерская при храме Алипия Печерского в Москве предлагает рукописные иконы на заказ. Для того чтобы **[заказать рукописную икону](https://www.st-alipy.ru/)** можно позвонить по телефону или обратиться по адресу м. Новокузнецкая, Пятницкая улица, 3/4 стр. График работы мастерской пн -пт с 10.00 до 21.00, сб. с 13.00 до 18.00. Вы также можете предварительно рассчитать стоимость изделия на сайте иконописной мастерской.

**Comment by Smucker** [comment]
«[Строитель России 2018](https://inter-regional.ru/stroitel-rossii.html)» — крупнейшее образовательное мероприятие страны для специалистов строительной сферы.
